version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3364:3364"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/apisolid?schema=public"
      NODE_ENV: dev
      PORT: 3364
      HOST: "0.0.0.0"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid