version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      DATABASE_URL: postgres://docker:docker@db:5432/apisolid
    ports:
      - "3364:3364"
    depends_on:
      - db
    volumes:
      - ./src:/usr/app/src  # Bind mount the 'src' directory to the container
      
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
      
